name: Download and Unzip latest AirConnect Release
on:
  push:
    branches:
      - ci
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
            path: '.'
      - name: Get Release Version
        id: get_release
        uses: robinraju/release-downloader@v1.8
        with: 
            repository: "philippe44/AirConnect"
            latest: true                        
            tarBall: false
            zipBall: false
            fileName: "AirConnect*.zip"
            # "downloads" => It will create directory $GITHUB_WORKSPACE/downloads
            out-file-path: "src/dsm7/bin"
            extract: true
      - name: Test downloaded Release
        id: test_release
        run: |
          RELEASE_VERSION=${{ steps.get_release.outputs.tag_name }}
          RELEASE_FILES=${{ fromJson(steps.get_release.outputs.downloaded_files)[0] }}
          echo "Using AirConnect version '${RELEASE_VERSION}'"
          echo "Using downloaded file: '${RELEASE_FILES}'"
          ls -ltR ${GITHUB_WORKSPACE}/src/dsm7/bin/

      - name: Shellcheck
        run: cd ${GITHUB_WORKSPACE}/src/dsm7; make shellcheck

      - name: Test packaging of x86_64
        run: cd ${GITHUB_WORKSPACE}/src/dsm7; ARCH=x86_64 make build

      - name: Test packaging of all architectures
        run: cd ${GITHUB_WORKSPACE}/src/dsm7; make build-all

      - name: Cleanup target
        run: cd ${GITHUB_WORKSPACE}/src/dsm7; make clean

      - name: Check dist
        run: ls -ltR ${GITHUB_WORKSPACE}/src/dsm7/dist/

      - name: Cleanup dist
        run: cd ${GITHUB_WORKSPACE}/src/dsm7; make clean-dist